# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of https://github.com/dehesselle/py3framework

name: build_inkscape
on: [push]

jobs:
  python_framework:
    runs-on: macos-10.15
    env:
      WRK_DIR: ${{ github.workspace }}/work
    steps:

    ### preparations ###########################################################

    # make build environment pristine
    - name: clear /usr/local
      run: sudo rm -rf /usr/local/*

    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    # GitHub does not provide the 10.11 SDK (from Xcode 7.3.1). There is no
    # official public download available from Apple and I don't trust 3rd
    # party sources (e.g. "phracker"), so I'm using my own source.
    - name: install MacOSX10.11.sdk (if secret is set)
      env:
        SDK1011_DOWNLOAD_URL: ${{ secrets.SDK1011_DOWNLOAD_URL }}
      if: env.SDK1011_DOWNLOAD_URL != null   # run if secret exists
      run:  |
            curl -L ${{ secrets.SDK1011_DOWNLOAD_URL }} | tar xJp
            echo "SDKROOT=$GITHUB_WORKSPACE/$(basename -s .tar.xz ${{ secrets.SDK1011_DOWNLOAD_URL }})"

    ### build ##################################################################

    - name: build dependencies
      uses: ./build-dependencies

    - name: build Python
      run: ./210a-build_python.sh

    - name: build Libxml2
      run: ./220-build_libxml2.sh

    - name: package Python framework
      run: ./310-package_framework.sh

    ### artifact ###############################################################

    - name: create archive
      run: tar -C $WRK_DIR/Frameworks -c Python.framework | xz -T 0 >$GITHUB_WORKSPACE/Python.framework.inkscape.tar.xz

    - name: upload archive
      uses: actions/upload-artifact@v2
      with:
        name: Python framework for Inkscape
        path: ${{ github.workspace }}/Python.framework.inkscape.tar.xz
