name: build_generic
on: [push]

jobs:
  build:
    runs-on: macos-10.15
    env:
      WRK_DIR: ${{ github.workspace }}/work
    steps:

    ### preparations ###########################################################

    # make build environment pristine
    - name: clear /usr/local
      run: sudo rm -rf /usr/local/*

    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    # GitHub does not provide the 10.11 SDK (from Xcode 7.3.1). There is no
    # official public download available from Apple and I don't trust 3rd
    # party sources (e.g. "phracker"), so I'm using my own source.
    - name: install MacOSX10.11.sdk (if secret is set)
      env:
        SDK1011_DOWNLOAD_URL: ${{ secrets.SDK1011_DOWNLOAD_URL }}
      if: env.SDK1011_DOWNLOAD_URL != null   # run if secret exists
      run:  |
            curl -L ${{ secrets.SDK1011_DOWNLOAD_URL }} | tar xJp
            echo "SDKROOT=$GITHUB_WORKSPACE/$(basename -s .tar.xz ${{ secrets.SDK1011_DOWNLOAD_URL }})"

    ### build ##################################################################

    - name: build libiconv
      run: ./110-build-iconv.sh
    - name: build zlib
      run: ./120-build-zlib.sh
    - name: build OpenSSL
      run: ./130-build-openssl.sh
    - name: build GNU readline
      run: ./140-build-readline.sh
    - name: build GNU gettext
      run: ./150-build-gettext.sh
    - name: build XZ utils (lzma)
      run: ./160-build-lzma.sh
    - name: build Python
      run: ./170-build-python.sh
    - name: build Libxml2
      run: ./180-build-libxml2.sh
    - name: package Python
      run: ./210-package.sh

    ### artifact ###############################################################

    - name: create archive
      run: tar -C $WRK_DIR/Frameworks -cJf $GITHUB_WORKSPACE/Python.framework.tar.xz Python.framework

    - name: upload archive
      uses: actions/upload-artifact@v2
      with:
        name: Python framework
        path: ${{ github.workspace }}/Python.framework.tar.xz
