# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of https://github.com/dehesselle/py3framework

name: build_inkscape
on: [push]

jobs:

################################################################################

  python_inkscape:
    runs-on: macos-10.15
    env:
      WRK_DIR: /Users/Shared/work
      CCACHE_DIR: /Users/Shared/work/ccache
    steps:

    ### prepare ################################################################

    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: create timestamp
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        format: "YYYY-MM-DD-HH-mm-ss"

    - name: populate CCACHE_DIR
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ steps.time.outputs.time }}
        restore-keys: ccache-

    # GitHub does not provide the 10.11 SDK (from Xcode 7.3.1). There is no
    # official public download available from Apple and I don't trust 3rd
    # party sources (e.g. "phracker"), so I'm using my own source.
    - name: install MacOSX10.11.sdk (if secret is set)
      env:
        SDK1011_DOWNLOAD_URL: ${{ secrets.SDK1011_DOWNLOAD_URL }}
      if: env.SDK1011_DOWNLOAD_URL != null
      run:  |
            mkdir -p $WRK_DIR
            curl -L ${{ secrets.SDK1011_DOWNLOAD_URL }} | tar -C $WRK_DIR -xJp
            echo "SDKROOT=$WRK_DIR/$(basename ${SDK1011_DOWNLOAD_URL%%.tar.xz*})" >> $GITHUB_ENV

    ### build: Python ##########################################################

    - name: build ccache
      run: ./110-build_ccache.sh

    - name: build libiconv
      run: ./120-build_iconv.sh

    - name: build zlib
      run: ./130-build_zlib.sh

    - name: build OpenSSL
      run: ./140-build_openssl.sh

    - name: build GNU readline
      run: ./150-build_readline.sh

    - name: build GNU gettext
      run: ./160-build_gettext.sh

    - name: build XZ utils (lzma)
      run: ./170-build_lzma.sh

    - name: build Python
      run: ./210a-build_python.sh

    - name: build Libxml2
      run: ./220-build_libxml2.sh

    - name: package Python framework
      run: ./310-package_framework.sh

    ### artifact: Python #######################################################

    - name: create Python archive
      run: tar -C $WRK_DIR/Frameworks -c Python.framework | xz -T 0 >$GITHUB_WORKSPACE/Python.framework.tar.xz

    - name: upload Python archive
      uses: actions/upload-artifact@v2
      with:
        name: Python framework for Inkscape
        path: ${{ github.workspace }}/Python.framework.tar.xz

    ### statistics #############################################################

    - name: print ccache statistics
      run: $WRK_DIR/bin/ccache -s